### PR TITLE
Added draft saving

### PR DESCRIPTION
**Pull request by ruddfawcett**

### CODE REVIEW

**Comment by dennisreimann** [comment]
Please use auto-synthesize, so that you don't have to state

```
@synthesize issueNumber, issueRepository;
```

You can then access the instance variables via _issueNumber, _issueRepository (or better yet, use the getters: self.issueNumber, self.issueRepository)

Also keep in mind, that the CommentController is also used for commenting on gists, pull requests and commits - it is not limited to issues.

One more note: I think we should use a simple key like   owner/repo/resource_type/resource_id for referencing the  temporary comment, what do you think?

**Comment by iosdeveloper** [comment]
Use getter/setter for properties and temporarily save in a singleton like `sharedApplication` or `iOctocat` instead of persisting to disk.

**Comment by dennisreimann** [comment]
If you need help or want to clarify somenthing, feel free to ask here :)

**Comment by dennisreimann** [comment]
> wouldn't a userDefault? It saves even if the app crashes/is terminated by user, doesn't it?

yes, that would also save it in case of a crash. in memory would also keep it (at least for some time) when leaving the app. I'd suggest you go with in memory storage.

> I was adding auto synthesize, but when passing the issue number and issue repository, it says ...

Are you sure that you were using the getter/setter with self.issueNumber and not just the instance variable issueNumber? (btw: autosynthesize generates instance vars prefixed with an underscore, so that would be _issueNumber).

**Comment by iosdeveloper** [comment]
Which version of Xcode are you using?

**Comment by iosdeveloper** [comment]
6f3edd0 does not compile for you without the `@synthesize`'s?

**Comment by iosdeveloper** [comment]
I would try

> Product => Clean

and maybe the `@property` declarations need to be above the `init` declaration in the header!?

**Comment by iosdeveloper** [comment]
Add to iOctocat class and use `[iOctocat sharedInstance]` from everywhere.

**Comment by dennisreimann** [comment]
Hello Rudd, thanks for driving this forward, I think it is going to be a nice feature.

I think we can keep it simpler than what it currently looks like and the best thing is that it would make it reusable for writing issues as well - here's what we should drive this towards:

Lets make it a Singleton (maybe call it TextDrafts) that is accessible throughout the app and holds the draft data in a NSDictionary instance. Here's what the accessor for that could look like:

``` objectivec
+ (instancetype)sharedInstance {
    static id sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [[self alloc] init];
        sharedInstance.drafts = [[NSDictionary alloc] init];
    });
    return sharedInstance;
}
```

This Singleton could have a getter method for saved drafts, like 
`[TextDrafts sharedInstance] draftForKey:@"dennisreimann/ioctocat/pull/299/comment"]`
And a setter for saving them: 
`[TextDrafts sharedInstance] saveDraft:@"This is what I think..." forKey:@"dennisreimann/ioctocat/pull/299/comment"]`

The setter gets called whenever one leaves the `CommentController` without actually saving the comment. When one opens the `CommentController` we check whether or not a draft for the given key exists - if so, we display the text.

We should think about how to generate the keys for the individual items (Issues, Pull Requests, Gists, Commits), but this would give us the flexibility to handle all these and even future use cases for drafts, without having to specify properties and types for every item type that we want to store drafts for.

Does this make sense?

**Comment by dennisreimann** [comment]
I don't think that this is something we should persist on the file system. In memory storage would keep it while it would be relevant and we wouldn't have to deal too much with cleaning up old state.

**Pull request closed without merging**
