### PR TITLE
retina tabbar icons

### PR DESCRIPTION
**Pull request by weakfl**
some retina icons (CC license)

### CODE REVIEW

**Comment by dennisreimann** [comment]
Thank you! Where are the icons from? We'd still need one for the search :)

**Comment by weakfl** [comment]
You're welcome. Actually the search icon should be retina already (i think you're using the apple stock icon, which comes with retina support).
Anyway, here's the link to the whole icon set, you should be able to find a search icon as well:
http://blog.twg.ca/2010/11/retina-display-icon-set/

**Comment by dennisreimann** [comment]
Thanks a lot! I'll dig through some more sets as we'll have to find some more graphics, because the feed icons i.e. aren't retina size either… I'll also work on the logo.

btw: You are right about the search icon!

**Comment by weakfl** [comment]
Nice, looking forward to more retina gfx :)

btw, here's another CC set with some nice icons you might find useful:
http://app-bits.com/free-icons.html

**Comment by dennisreimann** [comment]
Merged :)

**Pull request merged**
