### PR TITLE
New artwork!

### PR DESCRIPTION
**Pull request by reynaert1250**
Hope to make some people happy with this new look.

### CODE REVIEW

**Comment by EddieRingle** [comment]
You have to be careful when using the Octocat (or its likeness) in the app icon (that is, GitHub probably won't like it). See [this issue comment](https://github.com/slapperwan/gh4a/pull/33#issuecomment-1271344) and [the GitHub media README](https://github.com/github/media#readme).

That said, that's one beautiful icon. :)

**Comment by reynaert1250** [comment]
Thanks! I just mailed GitHub to ask them to look into it. Hope it will not cause any trouble. 

*\* Please don't pull this request until this is cleared.

**Comment by EddieRingle** [comment]
Perhaps it'll turn out alright. I created a [mash-up](https://github.com/eddieringle/hubroid/blob/348f524d35b957bf39e003c0c6a92fe8375eee27/res/drawable/icon.png) of the Android and the Octocat for [Hubroid](https://github.com/eddieringle/hubroid), so it's certainly possible that it'll get the go ahead (I emailed them as well prior to using it).

**Comment by dennisreimann** [comment]
Okay, I hope they allow use to use it as it looks really great! 
Regardless of how this turns out: Thanks so much for the effort you've put into this, I like it very much :)

**Comment by dennisreimann** [comment]
Roy, I guess you haven't ears from GitHub about this yet, am I right?
Alternatively: Would it be possible to reduce the inner part to just the pluses and minuses engraved?

**Comment by reynaert1250** [comment]
I finaly got an answer from GitHub. The icon violates the rules. :-( I will alter the icon and upload it. 

Roy

**Comment by dennisreimann** [comment]
@Roylodder I just wanted to ask about the progress with the new icon :)

**Comment by reynaert1250** [comment]
Hi! Was very busy with some client project. Planning to adjust the icon next week. Happy eastern!

**Comment by reynaert1250** [comment]
I got an email from GitHub! 

# // Please reply above this line

From: Sonya (GitHub Staff)
Subject: Icon - GitHub guidlines

Hi Roy,

It's fine for use.

Thanks,
Sonya

# 

Reply with #ignore to stop receiving notifications for this discussion.

I will adjust all the icons and put in another pull request.

**Comment by dennisreimann** [comment]
Nice, so I can close this one?

**Comment by reynaert1250** [comment]
Yes! :-)

**Pull request closed without merging**
