### PR TITLE
Improve accessibility

### PR DESCRIPTION
**Pull request by dusek**
Various small accessibility improvements. For more details please
see the individual commit messages.

Two major improvements are dependent on improving used libraries:
- ECSlidingViewController - I created https://github.com/edgecase/ECSlidingViewController/pull/127
  for this. Shall I also fork [ioctocat/ECSlidingViewController](https://github.com/ioctocat/ECSlidingViewController) and submit
  the same change there, or change it inline in the [dennisreimann/ioctocat](https://github.com/dennisreimann/ioctocat)
  repository?
- TTTAttributedLabel - each link and non-link segment should be a separate
  accessibility element. The EventCell should then also present all its
  elements separately for this to have effect. I hope to work on it
  the next weekend.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Thanks for your changes, I will review them during this week. Concerning the ECSlidingViewController: You need to fork the iOctocat fork of it and make the changes there.

**Comment by dusek** [comment]
> Concerning the ECSlidingViewController: You need to fork the iOctocat fork of it and make the changes there.

[done](https://github.com/iOctocat/ECSlidingViewController/pull/1)

**Comment by dennisreimann** [comment]
well done, thanks! :+1:

**Comment by dusek** [comment]
My pleasure :blush:

**Comment by dennisreimann** [comment]
I had to merge the changes manually because there where conflicts with a bunch of refactorings I pushed before, but your changes are on master now, thanks a lot!

**Pull request merged**
