### PR TITLE
Cache gravatar in the model.

### PR DESCRIPTION
**Pull request by zhen9ao**
Hope can solve the issue that gravatar will not automatically loaded if user is login with E-mail account.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Thanks for your contribution. IMHO caching the gravatar is not something the model should be concerned with. I'd rather move all of that gravatar code (except for the gravatarURL attribute) out of the model and handle this in the controller (iOctocat.m), because that's where it should be.

**Comment by zhen9ao** [comment]
Maybe it true that caching should be in the controller, but I think that would make the logic so complicated.

**Comment by dennisreimann** [comment]
I don't think so, because we can handle it directly [where we cache users and orgs](https://github.com/dennisreimann/ioctocat/blob/master/Classes/iOctocat.m#L220). Which btw should not be in the iOctocat class anyways. Let's refactor this and move the user and org caches to separate singletons. I could do this this evening, but I'd give you a go in case you'd like to do it.

**Comment by zhen9ao** [comment]
Yeah, I can give it a shot, but may not finish this evening....

Do you mean that put the user and org cache code to a separate singletone such as Services in the project?

**Comment by dennisreimann** [comment]
Exactly. To keep this simple, I'd first move this off into a separate service class (like IOCUserObjectsRepository) and delegate to that from iOctocat.sharedInstance, so that we don't have to change all our other classes (which we can do later on). Let me know what you think and whether or not you'd like to do it - this does not have to be done today, but I'd like to finish it this weekend.

**Comment by zhen9ao** [comment]
That would be best if you do some lead work first, I think finish it this weekend won't be a problem.

**Comment by dennisreimann** [comment]
Alright, I'll come up with something this evening. I'm also not sure if this should be a singleton or better yet an instance we can assign per account, so that we wouldn't even have to clear it on every "sign out" (everytime the user goes back to the menu).

**Comment by zhen9ao** [comment]
And maybe on another branch, say "development"?

**Pull request closed without merging**
