### PR TITLE
Change keyboard style to `E-mail Address` for `Login` input field.

### PR DESCRIPTION
**Pull request by zhen9ao**

### CODE REVIEW

**Comment by ruddfawcett** [comment]
You might want to take a look at this.  It gives the user an option for which keyboard to use... #361

**Comment by dennisreimann** [comment]
Even though you can use your email address as the login, it is discouraged, because it makes things more difficult afterwards (i.e. we cannot show the gravatar immediately)

**Comment by zhen9ao** [comment]
Yeah, maybe it's a bug not showing gravatar immediately in the AccountController if someone login with an E-mail account, because Github allows users to login not only with user name.

**Comment by dennisreimann** [comment]
You can also login via email address in iOctocat, but like I said it is discouraged. Changing the keyboard to the email style would encourage users to provide their email address rather than username.

**Comment by ghost** [comment]
Ah I see. But why not do both? Use the email style keyboard and add a little label 'We recommend to use your user name instead of an Email address'. If it's appreciated I'd implement it...

**Comment by dennisreimann** [comment]
Having the email style would encourage to put in the email address. Thanks for your contribution, but let's keep it as it is.

**Pull request closed without merging**
