### PR TITLE
Fix issue #201

### PR DESCRIPTION
**Pull request by zhen9ao**
Fix issue #201 : The "Authenticating..." label won't shown at the startup when there is one account.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Can you take a look at 68f1939 and see if it fixes the issue and works as you also intended it? Like I said, I think the awakeFromNib part is superfluous or did I miss something?

**Comment by zhen9ao** [comment]
Yeah, that works! Thanks!

**Comment by zhen9ao** [comment]
Although it works, I don't understand why `viewDidAppear` won't be called when MenuController poped out and AccountsController shown.

**Comment by dennisreimann** [comment]
It's because `viewDidAppear` only gets called once, when the view is shown for the first time, after its initialization - not everytime the view gets shown. I had the same misconception, but here's the extract from the Apple docs:

> Notifies the view controller that its view was added to a view hierarchy.

**Comment by zhen9ao** [comment]
I test it in a pure UINavigationController with two UIControllers(say controller1 and controller2), both the `viewWillAppear` and `viewDidAppear` of controller1 get called when controller2 was poped out. 
Also I test this situation in the example of `ECSlidingViewController` either in the TopViewController or in the UnderViewController, the view controller won't behave like what I got before.
so, is this a bug of ECSlidingViewController?

**Comment by dennisreimann** [comment]
I'll have to investigate this.

**Pull request closed without merging**
