### PR TITLE
Added option to Disable avatar downloading

### PR DESCRIPTION
**Pull request by MazyM**
I have added the option to disable an avatar downloading. Please review it.

### CODE REVIEW

**Comment by iosdeveloper** [comment]
Your implementation will disable avatar loading until the user opens our settings pane once.
I suggest changing the key to "Disable avatar loading", as then there will be no issues with the default value being `NO`.

**Comment by MazyM** [comment]
Thanks for the information. I thought the default value defined in the root.pfile is loaded without opening the Settings Pane once, but it was mistake.

**Comment by iosdeveloper** [comment]
Looking good! Will merge it in now. Thanks for contributing!

**Comment by dennisreimann** [comment]
Great, thank you!

**Pull request merged**
